### ISSUE TITLE
How to overwrite styles

### ISSUE THREAD

**Issue by oskarrough** [mansona/ember-cli-notifications#138]
I've just updated from 3.x to 4.x and it seems the addon is now using generated, unique classes for styling.

If so, how are we supposed to overwrite the styling? I ended up with the following. Which is a bit verbose compared to before :-)

```css
[class^="_c-notification__container--top-right"],
[class*=" _c-notification__container--top-right"],
.c-notification__container--top-right {
  top: 1rem;
}
```
